name: flutter_quiz
description: "Мобильное приложение для интерактивных квизов"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.1.0
  # file_picker: ^5.5.0
  syncfusion_flutter_charts: ^23.1.44
  intl: ^0.18.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true